owner: identitrain
repo: central.app.status

sites:
  - name: Identitrain Central
    url: https://central.identitrain.com

status-website:
  cname: status.identitrain.com
  logoUrl: https://central.identitrain.com/images/logo-nav.webp
  name: Identitrain Service Status
  introTitle: "**Identitrain** | Unlock your full potential in IAM"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
